server:
  port: 8081

spring:
  application:
    name: demo-customer
  main:
    allow-bean-definition-overriding: true

  redis:
    # redis服务器地址（默认为loaclhost）
    host: 127.0.0.1
    # redis端口（默认为6379）
    post: 6379
    # redis访问密码（默认为空）
    password: 123456
    # redis连接超时时间（单位毫秒）
    timeout: 0
eureka:
  #eueka 主机名
  instance:
    hostname: 127.0.0.1
  client:
    #提供者和消费者的注册地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
  hystrix:
    enabled: true

spring.datasource:
  name: develop
  url: jdbc:mysql://127.0.0.1:3306/oa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
#security配置
#security:
#  oauth2:
#    resource:
#      user-info-uri:http://localhost:8290/auth/user