
server:
  port: 8091

eureka:
  #eueka 主机名
  instance:
    hostname: localhost
  client:
    #提供者和消费者的注册地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    server:
      enableSelfPreservation : false

spring:
  application:
    name: demo-provider

spring.datasource:
  name: develop
  url: jdbc:mysql://127.0.0.1:3306/oa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  druid:
    #初始化时建立物理连接的个数
    initialSize: 1
    #池中最大连接数
    maxActive: 20
    #最小空闲连接
    minIdle: 1
    #获取连接时最大等待时间，单位毫秒
    maxWait: 60000
    #有两个含义：
    #1) Destroy线程会检测连接的间隔时间
    #如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
    #2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    timeBetweenEvictionRunsMillis: 60000
    #连接保持空闲而不被驱逐的最小时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #使用该SQL语句检查链接是否可用。
    #如果validationQuery=null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
    validationQuery: SELECT 1 FROM DUAL
    #建议配置为true，不影响性能，并且保证安全性。
    #申请连接的时候检测，
    #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties.druid.stat.mergeSql: true
    #connectionProperties.druid.stat.slowSqlMillis: 5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

  tomcat:
    max-active: 1200
    max-wait: 1000
    initial-wait : 500